# Generated by Django 4.2 on 2025-04-19 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('publisher', models.CharField(choices=[('original content', 'Original Content'), ('the guardian', 'The Guardian'), ('daily mail', 'Daily Mail'), ('the independant', 'The Independant'), ('daily telegraph', 'Daily Telegraph'), ('daily express', 'Daily Express'), ('the sun', 'The Sun'), ('financial times', 'Financial Times'), ('metro', 'Metro'), ('the times', 'The Times')], default='original content', max_length=32)),
                ('subject', models.CharField(choices=[('news', 'News'), ('sport', 'Sport'), ('culture', 'Culture'), ('opinion', 'Opinion'), ('lifestyle', 'Lifestyle'), ('reviews', 'Reviews'), ('travel', 'Travel')], default='news', max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, default='../slant-default-image_ff67lu', upload_to='images/')),
                ('body', models.TextField(blank=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
