# Generated by Django 4.2 on 2025-04-20 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publisher',
            field=models.CharField(choices=[('original content', 'Original Content'), ('the guardian', 'The Guardian'), ('daily mail', 'Daily Mail'), ('the independant', 'The Independant'), ('daily telegraph', 'Daily Telegraph'), ('daily express', 'Daily Express'), ('the sun', 'The Sun'), ('financial times', 'Financial Times'), ('metro', 'Metro'), ('the times', 'The Times'), ('other', 'Other')], default='original content', max_length=32),
        ),
        migrations.AlterField(
            model_name='article',
            name='subject',
            field=models.CharField(choices=[('news', 'News'), ('sport', 'Sport'), ('culture', 'Culture'), ('opinion', 'Opinion'), ('lifestyle', 'Lifestyle'), ('reviews', 'Reviews'), ('travel', 'Travel'), ('other', 'Other')], default='news', max_length=32),
        ),
    ]
