# Generated by Django 4.2 on 2025-05-23 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_alter_article_publisher_alter_article_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='link',
            field=models.CharField(default='link', max_length=255),
        ),
    ]
